# Generated by Django 4.2.16 on 2025-06-20 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowRequest',
        ),
    ]
