# Generated by Django 4.2.16 on 2025-07-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_delete_borrowrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='books.genre'),
        ),
    ]
