# Generated by Django 4.2.16 on 2025-07-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Romance', 'Romance'), ('Biography', 'Biography'), ('History', 'History'), ('Self-Help', 'Self-Help'), ('Literary Fiction', 'Literary Fiction'), ('Young Adult', 'Young Adult'), ("Children's", "Children's"), ('Poetry', 'Poetry'), ('Horror', 'Horror')], max_length=50, null=True),
        ),
    ]
