# Generated by Django 4.2.16 on 2025-07-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copies', '0002_alter_bookrequest_offered_book_and_more'),
        ('books', '0005_remove_bookcopy_book_remove_bookcopy_owner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookCopy',
        ),
    ]
