# Generated by Django 4.2.16 on 2025-07-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_delete_bookcopy'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copies',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
