# Generated by Django 5.2.3 on 2025-07-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='books_read',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_settings',
            field=models.JSONField(default={'show_email': False, 'show_location': True, 'show_reading_stats': True}),
        ),
        migrations.AddField(
            model_name='user',
            name='reading_goal',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='user',
            name='total_swaps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_genres',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='reading_preferences',
            field=models.JSONField(default=list),
        ),
    ]
