# Generated by Django 4.2.16 on 2025-07-08 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_bookcopy_book_remove_bookcopy_owner_and_more'),
        ('copies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='offered_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_in_swaps', to='books.book'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='requested_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to='books.book'),
        ),
    ]
